#!/usr/bin/env python3
"""CLEAN_AUTO_EPOCH_V1 — strict forward observation classifier (READ-ONLY).

Protocol per user contract (2026-08-14):
- Epoch starts 2026-08-13T17:41:00Z (after F7 + T84 + T87 landed).
- Each closure gets immutable classification: source / execution / eligibility.
- CLEAN requires: source=AUTO, execution=AUTO_EXECUTED, no manual intervention,
  no emergency/technical/phantom attribution, real entry+exit, full initial SL
  from Guardian OPEN log, fees present, funding present-or-0, UTC-consistent ts.
- actual_initial_risk = |entry − initial_SL| × quantity (NEVER MAE/MFE/reconstructed).
- CAP_LIMITED = True when notional hit MAX_NOTIONAL_PCT (20% equity) OR lot/min
  notional forced sizing (per trade_executor sizing path).
- NET_R = NET / actual_initial_risk. Configured risk = $0.50.

This script does NOT modify any production file: outputs go to
research/clean_epoch_v1/epoch_v1.jsonl + checkpoint CSVs.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path("/root/tradingos")
OUT_DIR = ROOT / "research" / "clean_epoch_v1"
EPOCH_START_UTC = "2026-08-13T17:41:00"   # epoch boundary (UTC)
CONFIGURED_RISK = 0.50
MAX_NOTIONAL_PCT = 0.20

# Market-class split (T97): allocation-relevant observation ONLY (no logic change).
STOCK_SYMBOLS = {
    "AAPLUSDT", "TSLAUSDT", "NVDAUSDT", "AMZNUSDT", "MSFTUSDT", "METAUSDT",
    "GOOGLUSDT", "NFLXUSDT", "AMDUSDT", "INTCUSDT", "SOXLUSDT", "SOXSUSDT",
    "KORUUSDT", "SNXXUSDT", "SPCXUSDT", "TQQQUSDT", "SQQQUSDT",
}

# ── data sources ──────────────────────────────────────────────────────────
TRADES = ROOT / "logs/trades/trade_results.jsonl"
MANUAL = ROOT / "memory/manual_signals.jsonl"
INTERV = ROOT / "memory/process_interventions.jsonl"
GUARD_EVENTS = OUT_DIR / "guardian_events_since_epoch.txt"
MODE = ROOT / "operations/trading_mode.json"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_jsonl(path: Path):
    rows = []
    if not path.exists():
        return rows
    for line in path.read_text(errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except Exception:
            continue
    return rows


def parse_guard_open(events_text: str):
    """Parse 'OPEN detected: SYM Side @ px qty=Q lev=5x SL=S TP=T' lines."""
    opens = {}
    for line in events_text.splitlines():
        if "OPEN detected" not in line:
            continue
        m = re.search(r"OPEN detected: (\S+) (\w+) @ ([\d.]+) qty=([\d.]+) lev=(\d+)x SL=([\d.]+) TP=([\d.]+)", line)
        if not m:
            continue
        sym, side, px, qty, lev, sl, tp = m.groups()
        # ts = the ISO timestamp inside the log line (UTC; guardian journal is UTC+3 local —
        # the ISO field itself is generated by python with tz; treat as UTC per epoch contract)
        ts_m = re.search(r"(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2})", line)
        opens.setdefault(sym, []).append({
            "ts": ts_m.group(1) if ts_m else "",
            "side": side, "entry": float(px), "qty": float(qty),
            "sl": float(sl), "tp": float(tp), "lev": int(lev),
        })
    return opens


def classify_trade(t: dict, manual_syms, interventions, guard_opens, equity):
    """Return (record, excluded_reason_or_None)."""
    ts = str(t.get("timestamp", ""))
    sym = t.get("symbol", "")
    rec = {
        "trade_id": t.get("trade_id") or t.get("id") or f"{ts}_{sym}",
        "symbol": sym,
        "side": t.get("side"),
        "entry": t.get("entry"),
        "exit": t.get("close_price"),
        "qty": t.get("size") or t.get("qty"),
        "net": t.get("net_pnl"),
        "gross": t.get("gross_pnl"),
        "fees": t.get("fees"),
        "mfe_peak_r": t.get("mfe_peak_r"),
        "mae_trough_r": t.get("mae_trough_r"),
        "guardian_trigger": t.get("guardian_trigger"),
        "signal_class": t.get("signal_class"),
        "be_fired": t.get("be_fired"),
        "partial_fired": t.get("partial_fired"),
        "tight_fired": t.get("tight_fired"),
        "outcome": t.get("outcome"),
        "ts": ts,
        "market_class": "STOCK" if sym in STOCK_SYMBOLS else "CRYPTO",
    }

    # ── 1. EPOCH BOUNDARY (UTC) ────────────────────────────────────────────
    try:
        ts_utc = ts[:19]
        if ts_utc < EPOCH_START_UTC:
            return rec, "PRE_EPOCH"
    except Exception:
        return rec, "TS_UNPARSEABLE"

    # ── 2. MANUAL CONTAMINATION ────────────────────────────────────────────
    # SQQQ-type: manual/shared path — presence in manual_signals with EXECUTED/
    # POSITION_CLOSED near this close ⇒ not clean AUTO even if symbol matches.
    if sym in manual_syms:
        return rec, "MANUAL_OR_SHARED_PATH"

    # ── 3. T84 INTERVENTIONS ───────────────────────────────────────────────
    for iv in interventions:
        if iv.get("symbol") == sym and not str(iv.get("symbol", "")).startswith("TEST"):
            if iv.get("event") == "PROCESS_INTERVENTION_BLOCKED":
                return rec, "INTERVENTION_ATTEMPT"

    # ── 4. INITIAL SL from Guardian OPEN log ───────────────────────────────
    opens = guard_opens.get(sym, [])
    if not opens:
        return rec, "NO_GUARDIAN_OPEN_SL"
    # pick the open whose ts is before close ts
    open_ = None
    for o in sorted(opens, key=lambda x: x["ts"]):
        if o["ts"] <= ts_utc:
            open_ = o
    if open_ is None:
        return rec, "NO_OPEN_BEFORE_CLOSE"
    entry = float(t.get("entry") or 0) or open_["entry"]
    sl_initial = open_["sl"]
    qty = float(t.get("size") or t.get("qty") or open_["qty"])
    actual_risk = abs(entry - sl_initial) * qty

    # ── 5. CAP_LIMITED ─────────────────────────────────────────────────────
    notional = entry * qty
    cap_limited = False
    cap_reason = ""
    if equity and notional >= equity * MAX_NOTIONAL_PCT * 0.95:
        cap_limited = True
        cap_reason = "MAX_NOTIONAL_PCT"
    # min_notional/lot force (cheap coins) — heuristic: risk per unit tiny
    if actual_risk < 0.5 * CONFIGURED_RISK and not cap_limited:
        cap_limited = True
        cap_reason = "LOT_OR_MIN_NOTIONAL_FORCE"

    rec.update({
        "initial_sl": sl_initial,
        "actual_initial_risk": round(actual_risk, 4),
        "configured_risk": CONFIGURED_RISK,
        "notional": round(notional, 2),
        "cap_limited": cap_limited,
        "cap_reason": cap_reason,
    })
    if t.get("net_pnl") is not None and actual_risk > 0:
        rec["net_r"] = round(float(t["net_pnl"]) / actual_risk, 4)
    else:
        rec["net_r"] = None

    # ── 6. EXECUTION / EXIT sanity ─────────────────────────────────────────
    if t.get("net_pnl") is None:
        return rec, "NO_NET"
    if t.get("fees") is None:
        return rec, "NO_FEES"
    rec["funding"] = t.get("funding", 0.0) or 0.0
    rec["slippage"] = t.get("slippage", None)  # recorded or None
    rec["source"] = "AUTO"
    rec["execution"] = "AUTO_EXECUTED"
    rec["eligibility"] = "CLEAN"
    rec["manual_intervention"] = False
    rec["market_class"] = "STOCK" if sym in STOCK_SYMBOLS else "CRYPTO"
    rec["classified_at"] = utc_now()
    return rec, None


def main():
    trades = load_jsonl(TRADES)
    manual_rows = load_jsonl(MANUAL)
    interventions = load_jsonl(INTERV)
    events_text = GUARD_EVENTS.read_text(errors="replace") if GUARD_EVENTS.exists() else ""
    guard_opens = parse_guard_open(events_text)

    manual_syms = set()
    for r in manual_rows:
        if r.get("event") in ("EXECUTED", "POSITION_CLOSED", "SIGNAL_SENT") and r.get("symbol"):
            manual_syms.add(r["symbol"])

    try:
        cfg = json.loads(MODE.read_text())
        equity = float(cfg.get("equity") or 0)
    except Exception:
        equity = 0.0
    if equity <= 0:
        # fall back to deposit guard last equity
        try:
            g = json.loads((ROOT / "operations/deposit_guard_state.json").read_text())
            equity = float(g.get("last_equity") or 0)
        except Exception:
            equity = 79.13

    clean, excluded = [], []
    for t in trades:
        rec, reason = classify_trade(t, manual_syms, interventions, guard_opens, equity)
        if reason:
            rec["eligibility"] = "EXCLUDED"
            rec["exclude_reason"] = reason
            excluded.append(rec)
        else:
            clean.append(rec)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with (OUT_DIR / "epoch_v1.jsonl").open("w") as f:
        for rec in sorted(clean, key=lambda x: x["ts"]):
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    with (OUT_DIR / "epoch_v1_excluded.jsonl").open("w") as f:
        for rec in sorted(excluded, key=lambda x: x["ts"]):
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"=== CLEAN_AUTO_EPOCH_V1 | equity≈${equity:.2f} | epoch≥{EPOCH_START_UTC}Z ===")
    print(f"CLEAN: {len(clean)} | EXCLUDED: {len(excluded)}")
    for r in clean:
        print(f"  CLEAN  {r['ts'][:16]} {r['symbol']:<10} {r['side']:<5} risk=${r['actual_initial_risk']:.3f} "
              f"cap={r['cap_reason'] or 'no':<18} net={r['net']:+.4f} net_r={r['net_r']}")
    print("\nEXCLUDED reasons:")
    from collections import Counter
    for reason, cnt in Counter(e["exclude_reason"] for e in excluded).most_common():
        print(f"  {reason}: {cnt}")


if __name__ == "__main__":
    main()
